// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Quizly.Data.Migrations
{
    [DbContext(typeof(QuizlyDbContext))]
    [Migration("20251111151204_ConfigureQuizQuestionRelationships")]
    partial class ConfigureQuizQuestionRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttemptDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedChoiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResultId");

                    b.HasIndex("SelectedChoiceId");

                    b.ToTable("AttemptDetails");
                });

            modelBuilder.Entity("Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "3"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "4"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "5"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "6"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "3"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "4"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "5"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "6"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "10"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "11"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "12"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "13"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "London"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = true,
                            QuestionId = 4,
                            Text = "Paris"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Berlin"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            QuestionId = 4,
                            Text = "Madrid"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "5"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "6"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = true,
                            QuestionId = 5,
                            Text = "7"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuestionId = 5,
                            Text = "8"
                        });
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Order = 1,
                            QuizId = 1,
                            Text = "What is 2 + 2?",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Order = 2,
                            QuizId = 1,
                            Text = "What is 10 - 5?",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Order = 3,
                            QuizId = 1,
                            Text = "What is 3 × 4?",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Order = 1,
                            QuizId = 2,
                            Text = "What is the capital of France?",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Order = 2,
                            QuizId = 2,
                            Text = "How many continents are there?",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedById = 1,
                            Description = "Test your basic math skills",
                            IsPublished = true,
                            Tags = "math, basic, arithmetic",
                            TimeLimitSeconds = 600,
                            Title = "Math Quiz - Basic"
                        },
                        new
                        {
                            Id = 2,
                            CreatedById = 1,
                            Description = "Test your general knowledge",
                            IsPublished = true,
                            Tags = "general, knowledge",
                            TimeLimitSeconds = 0,
                            Title = "General Knowledge"
                        });
                });

            modelBuilder.Entity("Quizly.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Administrator",
                            Email = "admin@quizly.com",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Test User",
                            Email = "user@quizly.com",
                            PasswordHash = "PnwZV2SIhigW8TtRLKzz5LqX3ZckPqC9airRZC2GunI=",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("AttemptDetail", b =>
                {
                    b.HasOne("Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Result", "Result")
                        .WithMany("Details")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Choice", "SelectedChoice")
                        .WithMany()
                        .HasForeignKey("SelectedChoiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Question");

                    b.Navigation("Result");

                    b.Navigation("SelectedChoice");
                });

            modelBuilder.Entity("Choice", b =>
                {
                    b.HasOne("Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.HasOne("Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Quiz", b =>
                {
                    b.HasOne("Quizly.Data.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Result", b =>
                {
                    b.HasOne("Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Quizly.Data.Models.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Quizly.Data.Models.User", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Result", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
